### ISSUE TITLE
OpenApi generator does not work - Toolbox remote call failed

### ISSUE THREAD

**Issue by lenguyenthanh** [http4k/toolbox-cli#1]
Command:
```
http4k generate openapi -l swagger.json -p some.package
```

Result:
```
Toolbox remote call failed. Please report this failure at http://github.com/http4k/toolbox-cli
https://cli.http4k.org/api/v1/openapi/file (400):
        TraceId=1f1614e7852c37ad%
```

I also tried it here: `https://toolbox.http4k.org/openapi` but didn't work.

**Comment by daviddenton** [comment]
Hey, Sorry about this - this i generally due to some edge-case quirk in the OpenApi spec. Are you able to share your OpenAPI spec that you're using to generate the client?

**Comment by lenguyenthanh** [comment]
Thanks for your quick reply!

________________________________

**Comment by lenguyenthanh** [comment]
Thanks for your quick reply!
I use Lichess Open Api spec, you can download it here: https://lichess.org/api

________________________________

**Comment by daviddenton** [comment]
I've tracked down the problem and there is a difference between the spec and what we've implemented:

```
Exception in thread "main" com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.http4k.openapi.generator.v3.OpenApi3ParameterSpec$QuerySpec] value failed for JSON property schema due to missing (therefore NULL) value for creator parameter schema which is a non-nullable type
 at [Source: (StringReader); line: 7092, column: 21] (through reference chain: org.http4k.openapi.generator.v3.OpenApi3Spec["paths"]->java.util.LinkedHashMap["/standard"]->org.http4k.openapi.generator.v3.OpenApi3VerbToPathSpec["get"]->org.http4k.openapi.generator.v3.OpenApi3PathSpec["parameters"]->java.util.ArrayList[0]->org.http4k.openapi.generator.v3.OpenApi3ParameterSpec$QuerySpec["schema"])
```

Digging into that, the offending JSON is: 

```
 "parameters": [
          {
            "in": "query",
            "name": "fen",
            "description": "FEN of the position. Underscores allowed. The halfmove clock is taken into account for WDL values."
          }
        ]
```

... which for us is bad because we expect a "schema" attribute to be there. this IS in the spec as optional, but we require it to be present currently. I suppose it should be a String by default - which we can fix. They do seem to have included the schema in a all of the other places, so if you add :
```
"schema": {
      "type": "string"
  },
``` 
to that parameter then the parsing works but it blows up a little later. I'll try and chase that through a bit more. I've uncovered at least one more bug which I'll also fix.

Stay tuned!

**Comment by daviddenton** [comment]
the good news is that this won't require a CLI release because the generation happens on the server

**Comment by lenguyenthanh** [comment]
oh This was quick, thanks! I'll with a small version of it.

**Comment by daviddenton** [comment]
ok. there was one other small problem which was the name of the api was illegal. I've fixed that and am pushing up a new version to the toolbox server. Should be there in the next 10 minutes or so.

Thanks for reporting the problem and feel free to reopen if you have any more problems.

**Comment by daviddenton** [comment]
that said, I've just noticed that there may be a problem with the `ApiUsersStatusJsonResponse200` class being missing when I generated the APi. it only affects one endpoint though - so you can still generate the entire thing and then remove that one (whilst I fix it)
